version: '3'

services:
  db_local:
    image: 'postgres:latest'
    container_name: hbo-ict-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}