version: '3'
# name: ve-prod

services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: ve-db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  init:
    image: visualengineer.azurecr.io/init:latest
    container_name: ve-db-init
    deploy:
      restart_policy:
        condition: on-failure
    build: 
      context: .
      dockerfile: init.Dockerfile
    environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
  backend:
    image: registry.gitlab.com/saxion.nl/hbo-ict/2.4-project/e1/dhi2ve1/backend:staging
    container_name: ve-backend
    domainname: visualengineer-api
    depends_on:
      - init
      - postgres
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
